### ISSUE TITLE
Right-click on the button was failed to show the windows

### ISSUE THREAD

**Issue by dicksonchow** [solacens/kube-tray#2]
First, I would like to show my greatest and sincerest appreciation of this project because it helps a lot to manage my Kubernetes configurations on my computer.

However, I have difficulties after I have followed your guide and installed the software on my computer. After I have managed to install the software, the button does show up on the top bar but it has no response when I put the mouse pointer on the icon and right-click.

I just wonder whether my configuration is correct. Kindly please suggest the solution so that I can use this software.

**Comment by solacens** [comment]
This problem has been fixed, probably due to malformed `~/.kube/utility_tray_config`.

For people experiencing this problem, I suggest running: 
```sh
rm ~/.kube/utility_tray_config
```
